branches:
  only:
    - master
language: python
sudo: false
matrix:
  include:
  - python: 3.6
  - services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    before_install:
      - if ! [[ $TRAVIS_TAG ]]; then exit 0; fi
    install:
      - docker pull $DOCKER_IMAGE
    script:
      - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
      - pip install twine && twine upload -u datamade.wheelbuilder -p $PYPIPASSWORD wheelhouse/*
      - exit 0
  - services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    before_install:
      - if ! [[ $TRAVIS_TAG ]]; then exit 0; fi
    install:
      - docker pull $DOCKER_IMAGE
    script:
      - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
      - pip install twine && twine upload -u datamade.wheelbuilder -p $PYPIPASSWORD wheelhouse/*
      - exit 0
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - cython src/*.pyx
  - pip install -e .
script:
  - pytest tests --cov dedupe
  - python tests/canonical.py -vv
cache:
  directories:
    - "$HOME/.cache/"
    - .cache
